# Generated by Django 5.1.2 on 2024-10-16 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='categorias',
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'verbose_name': 'Pregunta'},
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Examen.categoria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CategoriaPregunta',
        ),
    ]
