# Generated by Django 5.1.2 on 2024-10-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0002_remove_pregunta_categorias_alter_pregunta_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='image_url',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='image_url',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
